Repository plausible/analytics, pull requests merged in 2022-09, with the labels that each got.

#2152 Build Docker images for each PR
  .github/workflows/build-private-images.yml
  .github/workflows/build-public-images.yml
Labels: deploy-to-staging

#2222 Fix timezone input
  CHANGELOG.md
  lib/plausible/timezones.ex
  lib/plausible_web/templates/site/new.html.eex
  mix.exs
  mix.lock
  test/plausible/timezones_test.exs
Labels: deploy-to-staging

#2229 Sort timezone list by current offset
  lib/plausible/timezones.ex
Labels: bug

#2223 Ignore unknown country code
  CHANGELOG.md
  lib/plausible/stats/breakdown.ex
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
Labels: bug, sentry

#2216 Allow admins to grant admin rights
  lib/plausible/site/membership.ex
  lib/plausible_web/controllers/invitation_controller.ex
  lib/plausible_web/controllers/site/membership_controller.ex
  test/plausible_web/controllers/site/membership_controller_test.exs
Labels: bug, sentry

#2197 Manually lock outgrown enterprise accounts
  CHANGELOG.md
  guides/features/account-locking.md
  lib/plausible/auth/auth.ex
  lib/plausible/auth/grace_period.ex
  lib/plausible/auth/user.ex
  lib/plausible/auth/user_admin.ex
  lib/plausible/billing/billing.ex
  lib/plausible/billing/plans.ex
  lib/plausible/billing/site_locker.ex
  lib/plausible_web/email.ex
  lib/plausible_web/templates/email/dashboard_locked.html.eex
  lib/plausible_web/templates/email/enterprise_over_limit_internal.html.eex
  lib/plausible_web/templates/email/over_limit.html.eex
  lib/plausible_web/templates/layout/_notice.html.eex
  lib/plausible_web/views/layout_view.ex
  lib/workers/check_usage.ex
  mix.exs
  test/plausible/auth/auth_test.exs
  test/plausible/auth/grace_period_test.exs
  test/plausible/billing/plans_test.exs
  test/workers/check_usage_test.exs
  test/workers/lock_sites_test.exs
Labels: feature request

#2225 Fix shared link with bad auth
  CHANGELOG.md
  lib/plausible_web/controllers/stats_controller.ex
  mix.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
Labels: bug, sentry

#2244 Improve GA Imports error reporting
  lib/plausible/google/api.ex
  lib/plausible/google/http.ex
  lib/plausible/site/schema.ex
  test/plausible/google/api_test.exs
Labels: sentry, elixir

#2257 Fix favicons
  config/test.exs
  lib/plausible/http_client.ex
  lib/plausible_web/plugs/favicon.ex
  mix.exs
  mix.lock
  test/plausible/http_client_test.exs
  test/plausible_web/plugs/favicon_test.exs
  test/test_helper.exs
Labels: bug

#2254 Refresh Google Analytics token before import
  lib/plausible/google/api.ex
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/controllers/site_controller.ex
  lib/plausible_web/templates/site/import_from_google_confirm.html.eex
  lib/plausible_web/templates/site/import_from_google_user_metric_form.html.eex
  lib/plausible_web/templates/site/import_from_google_view_id_form.html.eex
  lib/workers/import_google_analytics.ex
  test/plausible/google/vcr_test.exs
  test/plausible_web/controllers/site_controller_test.exs
Labels: bug

#2273 Fix Google Analytics expires_at key
  lib/plausible/google/api.ex
  lib/plausible_web/controllers/auth_controller.ex
Labels: bug

#2034 International Domain Names (IDN) Support
  CHANGELOG.md
  lib/plausible/site/schema.ex
  lib/plausible_web/templates/site/settings_visibility.html.eex
  lib/plausible_web/views/stats_view.ex
  test/plausible_web/controllers/api/external_sites_controller_test.exs
  test/plausible_web/views/stats_view_test.exs
Labels: feature request
