Repository plausible/analytics, pull requests merged in 2022-10, with the labels that each got.

#2318 Delete stats improvements
  lib/oban_error_reporter.ex
  lib/plausible/clickhouse_repo.ex
  lib/plausible/imported/site.ex
  lib/plausible/purge.ex
  lib/plausible/sites.ex
  lib/plausible_web/controllers/api/external_sites_controller.ex
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/controllers/site_controller.ex
  lib/workers/import_google_analytics.ex
  test/plausible/purge_test.exs
Labels: bug, elixir

#2320 Add --host option to send_pageview task
  lib/mix/tasks/send_pageview.ex
Labels: elixir

#2332 Revert "Bump hexpm/elixir (#2239)"
  Dockerfile
Labels: deploy-to-staging

#2317 OpenTelemetry (OTEL) Implementation
  config/runtime.exs
  lib/plausible/application.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/open_telemetry.ex
  lib/plausible_web/controllers/api/external_controller.ex
  lib/plausible_web/plugs/auth_plug.ex
  lib/plausible_web/plugs/authorize_site_access.ex
  lib/plausible_web/plugs/authorize_stats_api.ex
  mix.exs
  mix.lock
Labels: deploy-to-staging, elixir

#2358 Google APIs integration improvements
  assets/js/dashboard/api.js
  assets/js/dashboard/stats/sources/search-terms.js
  lib/plausible/google/api.ex
  lib/plausible/google/http.ex
  lib/plausible/http_client.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/plausible_web/templates/site/settings_search_console.html.eex
  test/plausible/billing/billing_test.exs
  test/plausible/google/api_test.exs
  test/plausible/google/buffer_test.exs
  test/plausible/google/vcr_test.exs
  test/plausible/http_client_test.exs
  test/plausible/imported/imported_test.exs
  test/plausible/purge_test.exs
  test/plausible/site/admin_test.exs
  test/plausible/site/sites_test.exs
  test/plausible_web/captcha_test.exs
  test/plausible_web/controllers/api/external_sites_controller_test.exs
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
  test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/internal_controller_test.exs
  test/plausible_web/controllers/api/stats_controller/authorization_test.exs
  test/plausible_web/controllers/api/stats_controller/browsers_test.exs
  test/plausible_web/controllers/api/stats_controller/cities_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
  test/plausible_web/controllers/api/stats_controller/current_visitors_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
  test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/regions_test.exs
  test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
  test/plausible_web/controllers/auth_controller_test.exs
  test/plausible_web/controllers/billing_controller_test.exs
  test/plausible_web/controllers/invitation_controller_test.exs
  test/plausible_web/controllers/site/membership_controller_test.exs
  test/plausible_web/controllers/site_controller_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
  test/plausible_web/plugs/authorise_site_access_test.exs
  test/support/conn_case.ex
  test/support/data_case.ex
  test/support/test_utils.ex
  test/workers/check_usage_test.exs
  test/workers/import_google_analytics_test.exs
  test/workers/notify_annual_renewal_test.exs
  test/workers/send_email_report_test.exs
  test/workers/send_site_setup_emails_test.exs
  test/workers/send_trial_notifications_test.exs
Labels: deploy-to-staging

#2370 Clear stats_start_date after clearing GA stats
  lib/plausible/purge.ex
  test/plausible/purge_test.exs
Labels: bug

#2345 Suggest enterprise plan when usage is greater than 10M pageviews
  lib/plausible/billing/plans.ex
  test/workers/check_usage_test.exs
Labels: bug

#2381 Fix and test Google Analytics token refresh
  fixture/ga_refresh_token.json
  ga_report_imported_browsers.json
  ga_report_imported_devices.json
  ga_report_imported_entry_pages.json
  ga_report_imported_exit_pages.json
  ga_report_imported_locations.json
  ga_report_imported_operating_systems.json
  ga_report_imported_pages.json
  ga_report_imported_sources.json
  ga_report_imported_visitors.json
  lib/plausible/google/api.ex
  lib/plausible/google/http.ex
  test/plausible/google/api_test.exs
Labels: bug
