Repository plausible/analytics, pull requests merged in 2024-12, with the labels that each got.

#4805 Register segments schema
  lib/plausible/segment.ex
  test/plausible/segment_schema_test.exs
Labels: preview

#4863 APIv2: Case insensitive search
  CHANGELOG.md
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/devices/browser-versions-modal.js
  assets/js/dashboard/stats/modals/devices/browsers-modal.js
  assets/js/dashboard/stats/modals/devices/operating-system-versions-modal.js
  assets/js/dashboard/stats/modals/devices/operating-systems-modal.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/util/filters.js
  assets/js/types/query-api.d.ts
  lib/plausible/goals/filters.ex
  lib/plausible/google/search_console/filters.ex
  lib/plausible/stats/filters/filters.ex
  lib/plausible/stats/filters/legacy_dashboard_filter_parser.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/filters/stats_api_filter_parser.ex
  lib/plausible/stats/imported/base.ex
  lib/plausible/stats/imported/sql/where_builder.ex
  lib/plausible/stats/sql/special_metrics.ex
  lib/plausible/stats/sql/where_builder.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  priv/json-schemas/query-api-schema.json
  test/plausible/stats/query_parser_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Labels: preview

#4694 Add Plausible EE plugs in CE
  lib/plausible_web/mjml/templates/stats_report.mjml.eex
  lib/plausible_web/templates/email/spike_notification.html.heex
Labels: self-hosting

#4887 Average Scroll Depth Metric: dashboard sorting
  assets/js/dashboard/stats/reports/metrics.js
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
Labels: preview

#4889 Average Scroll Depth Metric: handle missing data better
  lib/plausible/data_migration/missing_scroll_depth.ex
  lib/plausible/ingestion/request.ex
  lib/plausible/stats/query_runner.ex
  lib/plausible/stats/sql/special_metrics.ex
  test/plausible_web/controllers/api/external_controller_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
Labels: preview

#4907 Bring back search by member email and name in Sites/Plans CRM
  lib/plausible/billing/enterprise_plan_admin.ex
  lib/plausible/crm_extensions.ex
  lib/plausible/site/admin.ex
Labels: preview

#4908 Migration: Add scroll_depth to imported_pages
  priv/ingest_repo/migrations/20241216133031_add_scroll_depth_to_imported_pages.exs
Labels: preview

#4911 Only show sites count in user CRM instead of full list of sites
  lib/plausible_web/controllers/admin_controller.ex
Labels: preview

#4913 Reimplement user search in enterprise plans CRM and fix plan prefill
  lib/plausible/billing/enterprise_plan.ex
  lib/plausible/crm_extensions.ex
  lib/plausible_web/controllers/admin_controller.ex
  lib/plausible_web/router.ex
Labels: preview

#4897 Hide billings and upgrade from CE
  lib/plausible_web/templates/layout/settings.html.heex
Labels: self-hosting, preview

#4919 Revert to `Sentry.LoggerBackend`
  config/runtime.exs
  lib/plausible/application.ex
Labels: preview

#4928 Show guest roles for other members in Site CRM
  lib/plausible/site/admin.ex
Labels: preview
