Repository plausible/analytics, pull requests merged in 2024-03, with the labels that each got.

#3844 Mutation to populate event session columns
  lib/plausible/data_migration.ex
  lib/plausible/data_migration/populate_event_session_columns.ex
  priv/data_migrations/PopulateEventSessionColumns/sql/create-sessions-dictionary.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/drop-sessions-dictionary.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/get-disks.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/get-merges-progress.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/get-mutations-progress.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/kill-running-mutations.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/list-partitions.sql.eex
  priv/data_migrations/PopulateEventSessionColumns/sql/update-table.sql.eex
Labels: deploy-to-staging

#3811 Dockerfile and co updates
  .dockerignore
  .github/workflows/build-public-images.yml
  CHANGELOG.md
  Dockerfile
  config/runtime.exs
  lib/plausible/geo.ex
Labels: deploy-to-staging

#3878 Replace caching engine
  lib/plausible/application.ex
  lib/plausible/cache.ex
  lib/plausible/cache/adapter.ex
  lib/plausible/cache/stats.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/session/cache_store.ex
  lib/plausible/shield/country_rule_cache.ex
  lib/plausible/shield/ip_rule_cache.ex
  lib/plausible/site/cache.ex
  lib/plausible/telemetry/plausible_metrics.ex
  mix.exs
  mix.lock
  test/plausible/cache/stats_test.exs
  test/plausible/cache_test.exs
  test/plausible/site/cache_test.exs
Labels: deploy-to-staging

#3903 remove init-admin.sh
  CHANGELOG.md
  rel/overlays/init-admin.sh
Labels: self-hosting

#3904 remove DISABLE_AUTH deprecation warning
  CHANGELOG.md
  config/runtime.exs
Labels: self-hosting

#3843 update Sentry
  Dockerfile
  config/config.exs
  config/runtime.exs
  lib/plausible/application.ex
  lib/plausible/sentry/client.ex
  lib/plausible_web/live/sentry_context.ex
  lib/sentry_filter.ex
  mix.exs
  mix.lock
  test/plausible_web/live/sentry_context_test.exs
Labels: deploy-to-staging

#3906 Allow importing extra config
  CHANGELOG.md
  mix.exs
  rel/overlays/import_extra_config.exs
  test/plausible/config_test.exs
Labels: self-hosting, deploy-to-staging

#3905 make robots.txt restrictive by default
  CHANGELOG.md
  lib/plausible_web/endpoint.ex
  priv/static/robots.txt
Labels: self-hosting

#3888 Unify UA and GA4 import flow into one
  fixture/ga4_get_property.json
  fixture/ga_start_date.json
  lib/plausible/google/api.ex
  lib/plausible/google/ga4/api.ex
  lib/plausible/google/ga4/http.ex
  lib/plausible/google/ua/api.ex
  lib/plausible/google/ua/http.ex
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/controllers/google_analytics4_controller.ex
  lib/plausible_web/controllers/google_analytics_controller.ex
  lib/plausible_web/router.ex
  lib/plausible_web/templates/google_analytics/confirm.html.heex
  lib/plausible_web/templates/google_analytics/property_or_view_form.html.heex
  lib/plausible_web/templates/google_analytics/user_metric_form.html.heex
  lib/plausible_web/templates/google_analytics4/confirm.html.heex
  lib/plausible_web/templates/google_analytics4/property_form.html.heex
  lib/plausible_web/templates/site/settings_imports_exports.html.heex
  lib/plausible_web/templates/universal_analytics/view_id_form.html.heex
  lib/plausible_web/views/google_analytics4_view.ex
  lib/plausible_web/views/google_analytics_view.ex
  lib/plausible_web/views/universal_analytics_view.ex
  priv/static/images/icon/google_analytics_4_logo.svg
  priv/static/images/icon/google_analytics_logo.svg
  test/plausible/google/api_test.exs
  test/plausible/google/ga4/api_test.exs
  test/plausible_web/controllers/google_analytics_controller_test.exs
  test/plausible_web/controllers/site_controller_test.exs
Labels: deploy-to-staging

#3919 Timeseries for conversion rate
  CHANGELOG.md
  assets/js/dashboard/stats/graph/graph-util.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  lib/plausible/stats/metrics.ex
  lib/plausible/stats/timeseries.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Labels: deploy-to-staging

#3918 Pages shield
  CHANGELOG.md
  lib/plausible/application.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/shield/country_rule.ex
  lib/plausible/shield/page_rule.ex
  lib/plausible/shield/page_rule_cache.ex
  lib/plausible/shields.ex
  lib/plausible/shields/country_test.exs
  lib/plausible/shields/ip_test.exs
  lib/plausible/shields/page_test.exs
  lib/plausible_web/controllers/site_controller.ex
  lib/plausible_web/live/shields/page_rules.ex
  lib/plausible_web/live/shields/pages.ex
  lib/plausible_web/templates/site/settings_shields.html.heex
  lib/plausible_web/views/layout_view.ex
  priv/repo/migrations/20240307083402_shield_page_rules.exs
  priv/repo/seeds.exs
  test/plausible/ingestion/event_test.exs
  test/plausible/shield/page_rule_cache_test.exs
  test/plausible/shields_test.exs
  test/plausible_web/live/shields/ip_addresses_test.exs
  test/plausible_web/live/shields/pages_test.exs
  test/test_helper.exs
Labels: deploy-to-staging

#3943 Implement adjusting imported date range to actual and existing stats
  fixture/ga4_end_date.json
  fixture/ga_end_date.json
  fixture/ga_start_date_later.json
  lib/plausible/google/api.ex
  lib/plausible/google/ga4/api.ex
  lib/plausible/google/ga4/http.ex
  lib/plausible/google/ua/api.ex
  lib/plausible/google/ua/http.ex
  lib/plausible/imported.ex
  lib/plausible_web/controllers/google_analytics_controller.ex
  lib/plausible_web/live/imports_exports_settings.ex
  lib/plausible_web/templates/google_analytics/confirm.html.heex
  lib/plausible_web/templates/google_analytics/user_metric_form.html.heex
  test/plausible/google/ga4/api_test.exs
  test/plausible/imported_test.exs
  test/plausible_web/controllers/google_analytics_controller_test.exs
Labels: deploy-to-staging
