Repository plausible/analytics, pull requests merged in 2024-07, with the labels that each got.

#4278 Fix new tab links + shared links losing URL context
  assets/js/dashboard.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/router.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/graph/stats-export.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/google-keywords.js
  assets/js/dashboard/stats/modals/modal.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/modals/table.js
  assets/js/dashboard/stats/more-link.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/search-terms.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/url.js
Labels: deploy-to-staging, preview

#4283 APIv2: Replace breakdown module with QueryBuilder
  CHANGELOG.md
  lib/plausible/stats/base.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/filters/where_builder.ex
  lib/plausible/stats/imported/base.ex
  lib/plausible/stats/imported/imported.ex
  lib/plausible/stats/metrics.ex
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_optimizer.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible/stats/sql/query_builder.ex
  lib/plausible/stats/table_decider.ex
  test/plausible/imported/csv_importer_test.exs
  test/plausible/imported/google_analytics4_test.exs
  test/plausible/stats/table_decider_test.exs
  test/plausible_web/controllers/CSVs/30d-filter-path/pages.csv
  test/plausible_web/controllers/CSVs/30d/pages.csv
  test/plausible_web/controllers/CSVs/6m/pages.csv
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
Labels: deploy-to-staging

#4297 Refactor Sites and Stats API authorization logic
  extra/lib/plausible_web/authorize_sites_api.ex
  lib/plausible_web/plugs/authorize_public_api.ex
  lib/plausible_web/plugs/authorize_stats_api.ex
  lib/plausible_web/router.ex
  test/plausible_web/controllers/api/external_sites_controller_test.exs
  test/plausible_web/plugs/authorize_public_api_test.exs
Labels: deploy-to-staging, preview

#4312 Remove Universal Analytics import logic
  fixture/ga_batch_report.json
  fixture/ga_end_date.json
  fixture/ga_list_views.json
  fixture/ga_report_empty_rows.json
  fixture/ga_report_imported_browsers.json
  fixture/ga_report_imported_devices.json
  fixture/ga_report_imported_entry_pages.json
  fixture/ga_report_imported_exit_pages.json
  fixture/ga_report_imported_locations.json
  fixture/ga_report_imported_operating_systems.json
  fixture/ga_report_imported_pages.json
  fixture/ga_report_imported_sources.json
  fixture/ga_report_imported_visitors.json
  fixture/ga_start_date.json
  fixture/ga_start_date_later.json
  lib/plausible/google/api.ex
  lib/plausible/google/ua/api.ex
  lib/plausible/google/ua/http.ex
  lib/plausible/google/ua/report_request.ex
  lib/plausible/imported.ex
  lib/plausible/imported/universal_analytics.ex
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/controllers/google_analytics_controller.ex
  lib/plausible_web/router.ex
  lib/plausible_web/templates/google_analytics/confirm.html.heex
  lib/plausible_web/templates/google_analytics/property_form.html.heex
  lib/plausible_web/templates/google_analytics/property_or_view_form.html.heex
  lib/plausible_web/templates/google_analytics/user_metric_form.html.heex
  test/plausible/google/api_test.exs
  test/plausible/imported/universal_analytics_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/google_analytics_controller_test.exs
Labels: deploy-to-staging, preview

#4323 Fix URLs breaking on date picker navigation
  assets/js/dashboard/query.js
Labels: preview

#4254 OS icons
  assets/js/dashboard/stats/devices/index.js
  priv/repo/seeds.exs
  priv/static/images/icon/os/android.png
  priv/static/images/icon/os/chrome_os.png
  priv/static/images/icon/os/fallback.svg
  priv/static/images/icon/os/fedora.png
  priv/static/images/icon/os/fire_os.png
  priv/static/images/icon/os/freebsd.png
  priv/static/images/icon/os/gnu_linux.png
  priv/static/images/icon/os/harmony_os.png
  priv/static/images/icon/os/ios.png
  priv/static/images/icon/os/ipad_os.png
  priv/static/images/icon/os/kai_os.png
  priv/static/images/icon/os/mac.png
  priv/static/images/icon/os/playstation.png
  priv/static/images/icon/os/tizen.png
  priv/static/images/icon/os/ubuntu.png
  priv/static/images/icon/os/windows.png
Labels: preview

#4333 fix(main-graph): fix 12mo and other comparisons with blanks
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Labels: preview

#4334 Alleviate props passing: institute UserContext, QueryContext, SiteContext
  assets/.eslintrc.json
  assets/js/dashboard.js
  assets/js/dashboard/comparison-input.js
  assets/js/dashboard/components/query-context-hoc.js
  assets/js/dashboard/datepicker.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/historical.js
  assets/js/dashboard/index.js
  assets/js/dashboard/query-context.js
  assets/js/dashboard/realtime.js
  assets/js/dashboard/router.js
  assets/js/dashboard/site-context.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/current-visitors.js
  assets/js/dashboard/stats/devices/index.js
  assets/js/dashboard/stats/graph/interval-picker.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/sources/index.js
  assets/js/dashboard/user-context.js
  assets/js/dashboard/util/filters.js
  assets/package-lock.json
Labels: preview

#4344 Open verification modal when following drop notification link
  assets/js/app.js
  lib/plausible_web/live/components/modal.ex
  lib/plausible_web/live/verification.ex
  lib/plausible_web/templates/email/drop_notification.html.eex
  lib/plausible_web/templates/site/settings_general.html.heex
  lib/workers/traffic_change_notifier.ex
  test/plausible_web/live/verification_test.exs
Labels: preview

#4340 Remove query and site props passing from everywhere except class components
  assets/js/dashboard/comparison-input.js
  assets/js/dashboard/components/notice.js
  assets/js/dashboard/datepicker.js
  assets/js/dashboard/extra/funnel.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/index.js
  assets/js/dashboard/query.js
  assets/js/dashboard/realtime.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/devices/index.js
  assets/js/dashboard/stats/graph/interval-picker.js
  assets/js/dashboard/stats/graph/stats-export.js
  assets/js/dashboard/stats/graph/top-stats.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/imported-query-unsupported-warning.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/filter-modal-group.js
  assets/js/dashboard/stats/modals/filter-modal-props-row.js
  assets/js/dashboard/stats/modals/filter-modal-row.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/sources/index.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/filters.js
Labels: preview

#4327 HelpScout integration
  config/.env.dev
  config/.env.test
  config/runtime.exs
  config/test.exs
  extra/lib/plausible/help_scout.ex
  extra/lib/plausible/help_scout/vault.ex
  extra/lib/plausible_web/controllers/help_scout_controller.ex
  extra/lib/plausible_web/views/help_scout_view.ex
  lib/plausible/application.ex
  lib/plausible/billing/plans.ex
  lib/plausible/sites.ex
  lib/plausible_release.ex
  lib/plausible_web/router.ex
  test/plausible/help_scout_test.exs
  test/plausible_web/controllers/help_scout_controller_test.exs
Labels: deploy-to-staging, preview

#4270 allow to configure Finch pools
  lib/plausible/application.ex
Labels: self-hosting

#4298 fix relay-without-auth mua config
  config/runtime.exs
  test/plausible/config_test.exs
Labels: self-hosting

#4350 Update bamboo_mua to disable mx lookups when relay is used
  CHANGELOG.md
  mix.lock
Labels: self-hosting

#4202 Improve PG unix sockets configuration
  CHANGELOG.md
  config/runtime.exs
  test/plausible/config_test.exs
Labels: self-hosting, deploy-to-staging, preview

#4338 Remove Timex.shift in app
  lib/mix/tasks/download_country_database.ex
  lib/plausible/auth/email_verification.ex
  lib/plausible/auth/grace_period.ex
  lib/plausible/auth/user.ex
  lib/plausible/billing/paddle_api.ex
  lib/plausible/billing/qouta/usage.ex
  lib/plausible/google/api.ex
  lib/plausible/stats.ex
  lib/plausible/stats/clickhouse.ex
  lib/plausible/stats/current_visitors.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/legacy/legacy_query_builder.ex
  lib/plausible/stats/time.ex
  lib/plausible/users.ex
  lib/workers/check_usage.ex
  lib/workers/schedule_email_reports.ex
  lib/workers/send_email_report.ex
Labels: preview

#4355 Show number of owned sites in HS integration with a link to sites list in CRM
  extra/lib/plausible/help_scout.ex
  extra/lib/plausible_web/views/help_scout_view.ex
  lib/plausible/site/admin.ex
  test/plausible/help_scout_test.exs
Labels: deploy-to-staging, preview

#4183 use nimble_csv everywhere
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/plausible_web/controllers/stats_controller.ex
  mix.exs
  mix.lock
Labels: preview

#4349 Fix debounce
  assets/js/dashboard/components/combobox.js
  assets/js/dashboard/custom-hooks.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/package-lock.json
  assets/package.json
Labels: preview

#4369 Implement UI to edit existing funnels
  CHANGELOG.md
  assets/tailwind.config.js
  config/dev.exs
  extra/lib/plausible/funnel.ex
  extra/lib/plausible/funnels.ex
  extra/lib/plausible_web/live/funnel_settings.ex
  extra/lib/plausible_web/live/funnel_settings/form.ex
  extra/lib/plausible_web/live/funnel_settings/list.ex
  lib/plausible_web/live/components/combo_box.ex
  test/plausible/funnels_test.exs
  test/plausible_web/live/components/combo_box_test.exs
  test/plausible_web/live/funnel_settings_test.exs
Labels: preview

#4366 Update Location library version
  mix.lock
Labels: preview

#4357 Remove Timex.today
  lib/mix/tasks/download_country_database.ex
  lib/plausible/auth/grace_period.ex
  lib/plausible/auth/user.ex
  lib/plausible/billing/paddle_api.ex
  lib/plausible/billing/qouta/usage.ex
  lib/plausible/billing/subscriptions.ex
  lib/plausible/google/ga4/http.ex
  lib/plausible/imported.ex
  lib/plausible/users.ex
  lib/plausible_web/components/billing/plan_box.ex
  lib/plausible_web/views/layout_view.ex
  lib/workers/check_usage.ex
  lib/workers/send_trial_notifications.ex
Labels: preview

#4382 Fix location labels
  assets/js/dashboard/stats/modals/locations-modal.js
Labels: preview

#4378 Implement search and pagination in Google Keywords modal
  assets/js/dashboard/api.js
  assets/js/dashboard/hooks/api-client.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/google-keywords.js
  assets/js/dashboard/stats/reports/metrics.js
  assets/js/dashboard/stats/sources/search-terms.js
  fixture/http_mocks/google_analytics_stats#with_page.json
  fixture/http_mocks/google_auth#invalid_grant.json
  fixture/http_mocks/google_search_console.json
  lib/plausible/google/api.ex
  lib/plausible/google/http.ex
  lib/plausible/google/search_console/filters.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible/google/api_test.exs
  test/plausible/google/search_console/filters_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/support/google_api_mock.ex
Labels: preview

#4384 Install newest @tanstack/react-router
  assets/js/dashboard.js
  assets/js/dashboard/comparison-input.js
  assets/js/dashboard/datepicker.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/query-context.js
  assets/js/dashboard/query.js
  assets/js/dashboard/router.js
  assets/js/dashboard/site-switcher.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/current-visitors.js
  assets/js/dashboard/stats/graph/line-graph.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/modal.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/more-link.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/search-terms.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/storage.js
  assets/js/dashboard/util/url.js
  assets/package-lock.json
  assets/package.json
Labels: preview

#4393 Revert "Install newest @tanstack/react-router (#4384)"
  assets/js/dashboard.js
  assets/js/dashboard/comparison-input.js
  assets/js/dashboard/datepicker.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/query-context.js
  assets/js/dashboard/query.js
  assets/js/dashboard/router.js
  assets/js/dashboard/site-switcher.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/current-visitors.js
  assets/js/dashboard/stats/graph/line-graph.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/modal.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/more-link.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/search-terms.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/storage.js
  assets/js/dashboard/util/url.js
  assets/package-lock.json
  assets/package.json
Labels: preview

#4394 Make time range filter for sessions not break sample size estimation
  lib/plausible/stats/sql/where_builder.ex
Labels: preview

#4377 Add ability to lookup by email and site domain in HelpScout integration
  extra/lib/plausible/help_scout.ex
  extra/lib/plausible_web/controllers/help_scout_controller.ex
  extra/lib/plausible_web/views/help_scout_view.ex
  lib/plausible_web/router.ex
  test/plausible/help_scout_test.exs
  test/plausible_web/controllers/help_scout_controller_test.exs
Labels: preview

#4400 Fix extraneous link fragment
  assets/js/dashboard/filters.js
Labels: preview

#4391 Generate goal filter SQL from postgres goals
  assets/js/dashboard/stats/modals/filter-modal-row.js
  extra/lib/plausible/stats/goal/revenue.ex
  lib/plausible/goals/filters.ex
  lib/plausible/goals/goals.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/filter_suggestions.ex
  lib/plausible/stats/filters/legacy_dashboard_filter_parser.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/filters/stats_api_filter_parser.ex
  lib/plausible/stats/filters/utils.ex
  lib/plausible/stats/imported/base.ex
  lib/plausible/stats/legacy/legacy_query_builder.ex
  lib/plausible/stats/query_result.ex
  lib/plausible/stats/sql/where_builder.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  test/plausible/stats/filters_test.exs
  test/plausible/stats/legacy_dashboard_filter_parser_test.exs
  test/plausible/stats/query_parser_test.exs
  test/plausible/stats/query_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_special_metrics_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/browsers_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
  test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
Labels: preview

#4404 Implement goal contains filter + search in Conversions > Details
  assets/js/dashboard/stats/modals/conversions.js
  lib/plausible/goals/filters.ex
  lib/plausible/stats/filters/query_parser.ex
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
Labels: preview

#4408 Update react-router to version 6
  assets/js/dashboard.js
  assets/js/dashboard/comparison-input.js
  assets/js/dashboard/datepicker.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/navigation/use-app-navigate.js
  assets/js/dashboard/query-context.js
  assets/js/dashboard/query.js
  assets/js/dashboard/router.js
  assets/js/dashboard/site-switcher.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/current-visitors.js
  assets/js/dashboard/stats/graph/line-graph.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/modal.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/more-link.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/search-terms.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/storage.js
  assets/js/dashboard/util/url.js
  assets/package-lock.json
  assets/package.json
Labels: preview

#4414 Stop JSONUrl parse failures from crashing the app
  assets/js/dashboard/util/url.js
Labels: preview
