Repository plausible/analytics, pull requests merged in 2024-06, with the labels that each got.

#4162 fix VersionedSessions migration
  lib/plausible/data_migration/versioned_sessions.ex
Labels: self-hosting

#4172 add newline to csv importer insert sql
  CHANGELOG.md
  lib/plausible/imported/csv_importer.ex
  test/plausible/imported/csv_importer_test.exs
Labels: self-hosting, deploy-to-staging, preview

#4165 fix registration in ce
  lib/plausible_web/live/register_form.ex
Labels: self-hosting

#4118 Implement filtering for imported data
  CHANGELOG.md
  assets/js/dashboard/historical.js
  assets/js/dashboard/index.js
  assets/js/dashboard/stats/behaviours/conversions.js
  assets/js/dashboard/stats/behaviours/goal-conversions.js
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/devices/index.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/imported-query-unsupported-warning.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/modals/table.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/source-list.js
  lib/plausible/imported.ex
  lib/plausible/stats/base.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/comparisons.ex
  lib/plausible/stats/email_report.ex
  lib/plausible/stats/filter_suggestions.ex
  lib/plausible/stats/imported/base.ex
  lib/plausible/stats/imported/imported.ex
  lib/plausible/stats/query.ex
  lib/plausible/stats/timeseries.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/browsers_test.exs
  test/plausible_web/controllers/api/stats_controller/cities_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
  test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
  test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/regions_test.exs
  test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Labels: deploy-to-staging, preview

#4187 Fix with imported switch + warning bubble renders
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/devices/index.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/graph/with-imported-switch.js
  assets/js/dashboard/stats/imported-query-unsupported-warning.js
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/sources/referrer-list.js
  assets/js/dashboard/stats/sources/source-list.js
  lib/plausible/stats/comparisons.ex
  lib/plausible/stats/query.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
Labels: deploy-to-staging, preview

#4208 Revert filters.js changes from 14cf650
  assets/js/dashboard/filters.js
Labels: deploy-to-staging, preview

#4092 Implement custom events suggestions
  lib/plausible/stats/goal_suggestions.ex
  lib/plausible_web/live/components/combo_box.ex
  lib/plausible_web/live/components/modal.ex
  lib/plausible_web/live/goal_settings.ex
  lib/plausible_web/live/goal_settings/form.ex
  lib/plausible_web/live/shields/country_rules.ex
  lib/plausible_web/live/shields/hostname_rules.ex
  lib/plausible_web/live/shields/page_rules.ex
  test/plausible/stats/goal_suggestions_test.exs
  test/plausible_web/live/goal_settings/form_test.exs
  test/plausible_web/live/goal_settings_test.exs
Labels: deploy-to-staging, preview

#4213 Reapply Filters component refactor + fix regression
  assets/js/dashboard/custom-hooks.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/index.js
Labels: deploy-to-staging, preview

#4221 Unify default pricing currency selection
  lib/plausible/application.ex
  lib/plausible/billing/paddle_api.ex
  lib/plausible/billing/plans.ex
  lib/plausible/cache/adapter.ex
  lib/plausible_release.ex
  lib/plausible_web/controllers/api/paddle_controller.ex
  lib/plausible_web/controllers/billing_controller.ex
  lib/plausible_web/live/choose_plan.ex
  lib/plausible_web/remote_ip.ex
  lib/plausible_web/router.ex
  lib/plausible_web/templates/billing/choose_plan.html.heex
  test/plausible/billing/paddle_api_test.exs
  test/plausible/billing/plans_test.exs
  test/plausible_web/controllers/api/paddle_controller_test.exs
  test/support/paddle_api_mock.ex
Labels: deploy-to-staging, preview

#4238 Reset captcha when captcha error is returned in registration form
  lib/plausible_web/live/register_form.ex
Labels: deploy-to-staging, preview

#4244 fix ce stats api access
  CHANGELOG.md
  lib/plausible/auth/auth.ex
  lib/plausible/billing/feature.ex
  test/plausible/auth/auth_test.exs
  test/plausible/billing/feature_test.exs
  test/plausible_web/controllers/api/external_stats_controller/auth_test.exs
  test/plausible_web/plugins/api/controllers/capabilities_test.exs
Labels: self-hosting

#4242 Fix pagination is Sites CRM
  lib/plausible/site/admin.ex
  test/plausible/site/admin_test.exs
  test/plausible_web/controllers/admin_controller_test.exs
Labels: deploy-to-staging, preview

#4252 Add backlinks between CRM, dashboard and site members
  lib/plausible/crm_extensions.ex
  lib/plausible_web/templates/layout/_header.html.heex
  lib/plausible_web/templates/site/settings_people.html.heex
  test/plausible_web/controllers/site_controller_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
Labels: deploy-to-staging, preview

#4253 Autoselect prop key
  CHANGELOG.md
  assets/js/dashboard/components/combobox.js
  assets/js/dashboard/stats/behaviours/props.js
  assets/js/dashboard/stats/reports/list.js
Labels: deploy-to-staging, preview

#4228 `does_not_contain`, new filters wildcard matching
  CHANGELOG.md
  assets/js/dashboard/components/filter-operator-selector.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/stats/modals/filter-modal-group.js
  assets/js/dashboard/stats/modals/filter-modal-props-row.js
  assets/js/dashboard/stats/modals/filter-modal-row.js
  assets/js/dashboard/util/filters.js
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/filters/where_builder.ex
  lib/plausible_web/controllers/stats_controller.ex
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
Labels: deploy-to-staging

#4263 Fix not so safe input
  lib/plausible/site/admin.ex
Labels: deploy-to-staging, preview

#4255 update runtime to elixir-1.17.1 and erlang-27.0
  .tool-versions
  Dockerfile
  lib/plausible_web/components/billing/plan_box.ex
  lib/plausible_web/templates/layout/focus.html.heex
  mix.exs
  mix.lock
  test/plausible_web/components/billing/notice_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
  test/plausible_web/live/components/combo_box_test.exs
  test/plausible_web/live/components/form_test.exs
  test/plausible_web/live/components/verification_test.exs
  test/support/live_view_test_fix.ex
Labels: deploy-to-staging, preview

#4245 happy tcp
  CHANGELOG.md
  config/runtime.exs
  lib/plausible/application.ex
  mix.exs
  mix.lock
Labels: self-hosting

#4276 Make new tab dashboard links work
  assets/js/dashboard.js
  assets/js/dashboard/router.js
Labels: deploy-to-staging, preview

#4251 APIv2: Aggregates, timeseries, conversion_rate, hostname
  lib/plausible/stats/aggregate.ex
  lib/plausible/stats/base.ex
  lib/plausible/stats/filters/filters.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/filters/utils.ex
  lib/plausible/stats/imported/imported.ex
  lib/plausible/stats/metrics.ex
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_optimizer.ex
  lib/plausible/stats/query_result.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible/stats/sql/query_builder.ex
  lib/plausible/stats/table_decider.ex
  lib/plausible/stats/util.ex
  test/plausible/stats/query_optimizer_test.exs
  test/plausible/stats/query_parser_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Labels: deploy-to-staging
