Repository plausible/analytics, pull requests merged in 2024-09, with the labels that each got.

#4495 Fix invalid parameter destructuring in `navigate` calls
  assets/js/dashboard/filters.js
  assets/js/dashboard/stats/graph/line-graph.js
Labels: preview

#4469 Support realtime periods in API v2
  lib/plausible/google/api.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/clickhouse.ex
  lib/plausible/stats/comparisons.ex
  lib/plausible/stats/datetime_range.ex
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/goal_suggestions.ex
  lib/plausible/stats/imported/base.ex
  lib/plausible/stats/imported/sql/builder.ex
  lib/plausible/stats/interval.ex
  lib/plausible/stats/json_schema.ex
  lib/plausible/stats/legacy/legacy_query_builder.ex
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_optimizer.ex
  lib/plausible/stats/query_result.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible/stats/sql/where_builder.ex
  lib/plausible/stats/time.ex
  lib/plausible/stats/timeseries.ex
  lib/plausible/timezones.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  priv/json-schemas/query-api-schema.json
  test/plausible/google/api_test.exs
  test/plausible/stats/comparisons_test.exs
  test/plausible/stats/interval_test.exs
  test/plausible/stats/query_optimizer_test.exs
  test/plausible/stats/query_parser_test.exs
  test/plausible/stats/query_result_test.exs
  test/plausible/stats/query_test.exs
  test/plausible/stats/time_test.exs
  test/plausible/timezones_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Labels: preview

#4418 Data migration for capitalizing sources
  priv/ingest_repo/migrations/20240801091615_capitalize_known_sources.exs
Labels: preview

#4472 Fix documentation link for Google integration
  lib/plausible_web/templates/site/settings_search_console.html.heex
  test/plausible_web/controllers/site_controller_test.exs
Labels: self-hosting

#4463 Implement token-based sessions
  CHANGELOG.md
  config/runtime.exs
  lib/plausible/auth/user.ex
  lib/plausible/auth/user_session.ex
  lib/plausible/users.ex
  lib/plausible_web.ex
  lib/plausible_web/live/auth_context.ex
  lib/plausible_web/live/sentry_context.ex
  lib/plausible_web/plugs/auth_plug.ex
  lib/plausible_web/plugs/last_seen_plug.ex
  lib/plausible_web/plugs/session_timeout_plug.ex
  lib/plausible_web/plugs/super_admin_only_plug.ex
  lib/plausible_web/plugs/user_session_touch.ex
  lib/plausible_web/router.ex
  lib/plausible_web/user_auth.ex
  lib/workers/clean_user_sessions.ex
  test/plausible_web/controllers/api/stats_controller/browsers_test.exs
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
  test/plausible_web/controllers/api/stats_controller/operating_systems_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/screen_sizes_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
  test/plausible_web/controllers/auth_controller_test.exs
  test/plausible_web/controllers/page_controller_test.exs
  test/plausible_web/controllers/site_controller_test.exs
  test/plausible_web/live/sentry_context_test.exs
  test/plausible_web/plugs/auth_plug_test.exs
  test/plausible_web/plugs/session_timeout_plug_test.exs
  test/plausible_web/plugs/user_session_touch_test.exs
  test/plausible_web/user_auth_test.exs
  test/support/test_utils.ex
  test/workers/clean_user_sessions_test.exs
Labels: preview

#4500 Fix HTML-in-JSON in ErrorView
  lib/plausible_web/views/error_view.ex
  test/plausible_web/views/error_view_test.exs
Labels: preview

#4485 Better Google error messages in CE
  CHANGELOG.md
  fixture/ga4_api_disabled_error.json
  lib/plausible/google/ga4/http.ex
  lib/plausible_web/controllers/google_analytics_controller.ex
  test/plausible/imported/google_analytics4_test.exs
  test/plausible_web/controllers/google_analytics_controller_test.exs
Labels: self-hosting

#4476 Add better assets compression to CE
  CHANGELOG.md
  Dockerfile
  config/ce.exs
  lib/plausible_web/endpoint.ex
  mix.exs
  mix.lock
Labels: self-hosting

#4474 Update bamboo_mua to fix headers issue
  CHANGELOG.md
  mix.lock
Labels: self-hosting

#4496 Adapt site_setup_success email for CE
  lib/plausible_web/templates/email/site_setup_success_email.html.eex
  test/plausible_web/email_test.exs
Labels: self-hosting

#4522 Imported disabled graph notice
  CHANGELOG.md
  assets/js/dashboard/stats/graph/visitor-graph.js
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_result.ex
  lib/plausible/stats/timeseries.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/plausible_web/controllers/stats_controller.ex
  test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
Labels: preview

#4482 Return domain-less cookies in CE
  CHANGELOG.md
  lib/plausible_web/endpoint.ex
Labels: self-hosting

#4528 Replace native tooltips with simplified, generic component
  lib/plausible_web/components/billing/plan_box.ex
  lib/plausible_web/components/generic.ex
  lib/plausible_web/live/imports_exports_settings.ex
  lib/plausible_web/live/installation.ex
  lib/plausible_web/live/shields/country_rules.ex
  lib/plausible_web/live/shields/hostname_rules.ex
  lib/plausible_web/live/shields/ip_rules.ex
  lib/plausible_web/live/shields/page_rules.ex
  test/plausible_web/live/choose_plan_test.exs
  test/plausible_web/live/shields/countries_test.exs
  test/plausible_web/live/shields/ip_addresses_test.exs
Labels: preview

#4539 Fix tzdata
  .github/workflows/elixir.yml
  config/runtime.exs
  mix.exs
  mix.lock
Labels: preview

#4494 Make ClickhouseRepo task timeouts configurable in CE
  lib/plausible/clickhouse_repo.ex
Labels: self-hosting

#4466 Run migrations in order across repos
  .github/workflows/elixir.yml
  CHANGELOG.md
  lib/plausible_release.ex
  rel/overlays/migrate.sh
  rel/overlays/pending-migrations.sh
  test/plausible/release_test.exs
  test/test_helper.exs
Labels: self-hosting, preview

#4546 Remove Timex.now
  lib/plausible/auth/user_admin.ex
  lib/plausible/data_migration/populate_event_session_columns.ex
  lib/plausible/data_migration/versioned_sessions.ex
  lib/plausible/google/api.ex
  lib/plausible/session/salts.ex
  lib/plausible/stats/comparisons.ex
  lib/plausible/stats/legacy/legacy_query_builder.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/workers/schedule_email_reports.ex
  lib/workers/send_email_report.ex
  lib/workers/send_site_setup_emails.ex
  test/plausible/stats/query_test.exs
Labels: preview

#4553 Filter modal fixes
  assets/js/dashboard/components/combobox.js
  assets/js/dashboard/components/filter-operator-selector.js
  assets/js/dashboard/last-load-context.tsx
  assets/js/dashboard/query-context.tsx
  assets/js/dashboard/router.tsx
  assets/js/dashboard/stats/current-visitors.js
  assets/js/dashboard/stats/graph/top-stats.js
  assets/js/dashboard/stats/modals/filter-modal-props-row.js
  assets/js/dashboard/stats/modals/filter-modal-row.js
  assets/js/dashboard/util/filters.js
Labels: preview

#4491 Auto HTTPS in CE
  CHANGELOG.md
  Dockerfile
  config/runtime.exs
  lib/plausible/application.ex
  lib/plausible_web/endpoint.ex
  mix.exs
  mix.lock
Labels: self-hosting, preview

#4513 Allow sorting breakdown lists by some metrics
  CHANGELOG.md
  assets/js/dashboard/components/search-input.tsx
  assets/js/dashboard/components/sort-button.tsx
  assets/js/dashboard/components/table.tsx
  assets/js/dashboard/datepicker.tsx
  assets/js/dashboard/hooks/api-client.js
  assets/js/dashboard/hooks/api-client.ts
  assets/js/dashboard/hooks/use-order-by.test.ts
  assets/js/dashboard/hooks/use-order-by.ts
  assets/js/dashboard/keybinding.tsx
  assets/js/dashboard/stats/graph/interval-picker.js
  assets/js/dashboard/stats/locations/map.tsx
  assets/js/dashboard/stats/modals/breakdown-modal.js
  assets/js/dashboard/stats/modals/breakdown-modal.tsx
  assets/js/dashboard/stats/modals/breakdown-table.tsx
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/devices/browser-versions-modal.js
  assets/js/dashboard/stats/modals/devices/browsers-modal.js
  assets/js/dashboard/stats/modals/devices/choose-metrics.js
  assets/js/dashboard/stats/modals/devices/operating-system-versions-modal.js
  assets/js/dashboard/stats/modals/devices/operating-systems-modal.js
  assets/js/dashboard/stats/modals/devices/screen-sizes.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/google-keywords.js
  assets/js/dashboard/stats/modals/google-keywords.tsx
  assets/js/dashboard/stats/modals/locations-modal.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/pages/index.js
  assets/js/dashboard/stats/reports/metrics.js
  lib/plausible/stats/breakdown.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
Labels: preview

#4512 Prepare for CE docs on Wiki for the upcoming release
  config/runtime.exs
  lib/plausible_web/templates/site/settings_search_console.html.heex
Labels: self-hosting

#4559 Breakdown modal search shortcut
  assets/js/dashboard/components/search-input.tsx
  assets/js/dashboard/stats/modals/breakdown-modal.tsx
Labels: preview

#4582 Drop event explicitly on session lock timeout
  lib/plausible/cache/adapter.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/session/cache_store.ex
  test/plausible/ingestion/event_test.exs
  test/plausible/session/cache_store_test.exs
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_goal_dimension_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_imported_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/funnels_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
  test/support/test_utils.ex
Labels: preview

#4540 Remove support for legacy user sessions
  lib/plausible_web/live/reset_password_form.ex
  lib/plausible_web/plugs/session_timeout_plug.ex
  lib/plausible_web/plugs/user_session_touch.ex
  lib/plausible_web/router.ex
  lib/plausible_web/user_auth.ex
  test/plausible_web/live/reset_password_form_test.exs
  test/plausible_web/plugs/session_timeout_plug_test.exs
  test/plausible_web/plugs/user_session_touch_test.exs
  test/plausible_web/user_auth_test.exs
Labels: preview

#4586 Solve build failure
  Dockerfile
Labels: preview

#4589 Fix applying city filters
  lib/plausible/stats/filter_suggestions.ex
  test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
Labels: preview

#4583 Refactor `AuthorizeSiteAccess`
  lib/plausible_web/controllers/google_analytics_controller.ex
  lib/plausible_web/controllers/invitation_controller.ex
  lib/plausible_web/controllers/site/membership_controller.ex
  lib/plausible_web/controllers/site_controller.ex
  lib/plausible_web/controllers/stats_controller.ex
  lib/plausible_web/plugs/authorize_site_access.ex
  lib/plausible_web/router.ex
  test/plausible_web/controllers/site_controller_test.exs
  test/plausible_web/plugs/authorise_site_access_test.exs
  test/plausible_web/plugs/authorize_site_access_test.exs
Labels: preview

#4585 Add feature-flagged channels UI
  assets/js/dashboard/router.tsx
  assets/js/dashboard/stats/modals/filter-modal.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/sources/source-list.js
  assets/js/dashboard/util/filters.js
  lib/plausible/stats/filter_suggestions.ex
  lib/plausible/stats/filters/filters.ex
  lib/plausible/stats/legacy/legacy_dimensions.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/plausible_web/controllers/stats_controller.ex
  lib/plausible_web/router.ex
  priv/json-schemas/query-api-schema.json
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/sources_test.exs
  test/plausible_web/controllers/api/stats_controller/suggestions_test.exs
Labels: preview

#4592 enrich with information about app node
  config/runtime.exs
  lib/plausible/open_telemetry.ex
Labels: preview

#4596 Don't render empty list element in CE
  lib/plausible_web/templates/auth/login_form.html.heex
Labels: self-hosting

#4605 Fix progress header not showing up when adding a new site
  lib/plausible_web/live/sites.ex
Labels: preview

#4604 Skip verification in CE
  lib/plausible_web/live/verification.ex
  test/plausible_web/live/verification_test.exs
Labels: preview

#4611 Implement user notes in CRM and HelpScout integration
  extra/lib/plausible/help_scout.ex
  extra/lib/plausible_web/views/help_scout_view.ex
  lib/plausible/auth/user.ex
  lib/plausible/auth/user_admin.ex
  test/plausible_web/controllers/help_scout_controller_test.exs
Labels: preview

#4621 Change cookie key in CE
  lib/plausible_web/endpoint.ex
Labels: preview

#4598 Use `:domain` uniformly for all routes instead of `:website`
  lib/plausible_web/controllers/site_controller.ex
  lib/plausible_web/controllers/unsubscribe_controller.ex
  lib/plausible_web/live/installation.ex
  lib/plausible_web/live/verification.ex
  lib/plausible_web/plugs/authorize_site_access.ex
  lib/plausible_web/router.ex
  test/plausible_web/controllers/google_analytics_controller_test.exs
  test/plausible_web/controllers/invitation_controller_test.exs
  test/plausible_web/controllers/site/membership_controller_test.exs
  test/plausible_web/controllers/site_controller_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
  test/plausible_web/controllers/unsubscribe_controller_test.exs
  test/plausible_web/live/funnel_settings_test.exs
  test/plausible_web/live/goal_settings_test.exs
  test/plausible_web/live/plugins_api_tokens_test.exs
  test/plausible_web/live/props_settings_test.exs
  test/plausible_web/plugs/authorize_site_access_test.exs
Labels: preview

#4597 Allow configuring `AuthorizeSiteAccess` plug site param
  config/dev.exs
  lib/plausible_web/plugs/authorize_site_access.ex
  lib/plausible_web/router.ex
  test/plausible_web/controllers/api/internal_controller/docs_query_test.exs
  test/plausible_web/plugs/authorize_site_access_test.exs
  test/support/test_controller.ex
Labels: preview

#4631 Start TOTP vault early
  lib/plausible/application.ex
Labels: preview

#4588 Implement listing user sessions in user settings
  CHANGELOG.md
  lib/plausible/auth/user_sessions.ex
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/router.ex
  lib/plausible_web/templates/auth/user_settings.html.heex
  lib/plausible_web/user_auth.ex
  test/plausible/auth/user_sessions_test.exs
  test/plausible_web/controllers/auth_controller_test.exs
  test/plausible_web/user_auth_test.exs
Labels: preview

#4624 Experimental pageleave events
  extra/lib/plausible_web/dogfood.ex
  lib/plausible/goal/schema.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/session/cache_store.ex
  lib/plausible/stats/aggregate.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/clickhouse.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible_web/plugs/tracker.ex
  test/plausible/billing/quota_test.exs
  test/plausible/goals_test.exs
  test/plausible/ingestion/event_test.exs
  test/plausible/session/cache_store_test.exs
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
  tracker/compile.js
  tracker/src/plausible.js
Labels: preview

#4640 Handle cross-device file move
  lib/plausible/file.ex
  lib/plausible_web/live/csv_import.ex
  lib/workers/export_analytics.ex
Labels: self-hosting, preview
