Repository plausible/analytics, pull requests merged in 2024-05, with the labels that each got.

#4061 run Oban in CE too
  config/runtime.exs
Labels: self-hosting

#4033 Add support for imported custom events
  CHANGELOG.md
  fixture/ga4_report_imported_custom_events.json
  lib/plausible/google/ga4/http.ex
  lib/plausible/google/ga4/report_request.ex
  lib/plausible/imported.ex
  lib/plausible/imported/buffer.ex
  lib/plausible/imported/custom_event.ex
  lib/plausible/imported/google_analytics4.ex
  lib/plausible/stats/aggregate.ex
  lib/plausible/stats/base.ex
  lib/plausible/stats/breakdown.ex
  lib/plausible/stats/imported.ex
  lib/plausible/stats/query.ex
  lib/plausible_web/controllers/api/external_stats_controller.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/workers/clickhouse_clean_sites.ex
  test/plausible/imported/google_analytics4_test.exs
  test/plausible/purge_test.exs
  test/plausible/stats/query_test.exs
  test/plausible_web/controllers/api/external_stats_controller/aggregate_test.exs
  test/plausible_web/controllers/api/external_stats_controller/breakdown_test.exs
  test/plausible_web/controllers/api/external_stats_controller/timeseries_test.exs
  test/plausible_web/controllers/api/stats_controller/conversions_test.exs
  test/plausible_web/controllers/api/stats_controller/custom_prop_breakdown_test.exs
  test/support/factory.ex
Labels: deploy-to-staging

#4093 Autoconfigure event goals
  lib/plausible/goal/schema.ex
  lib/plausible/goals.ex
  lib/plausible/stats/goal_suggestions.ex
  lib/plausible_web/live/goal_settings.ex
  lib/plausible_web/live/goal_settings/form.ex
  lib/plausible_web/live/goal_settings/list.ex
  test/plausible/stats/goal_suggestions_test.exs
  test/plausible_web/live/goal_settings_test.exs
Labels: deploy-to-staging

#4080 update links to configs
  config/runtime.exs
Labels: self-hosting

#4106 Snippet integration verification
  CHANGELOG.md
  Makefile
  assets/tailwind.config.js
  config/.env.dev
  config/runtime.exs
  config/test.exs
  extra/lib/plausible/ingestion/event/revenue.ex
  lib/plausible/ingestion/event.ex
  lib/plausible/verification.ex
  lib/plausible/verification/check.ex
  lib/plausible/verification/checks.ex
  lib/plausible/verification/checks/csp.ex
  lib/plausible/verification/checks/fetch_body.ex
  lib/plausible/verification/checks/installation.ex
  lib/plausible/verification/checks/scan_body.ex
  lib/plausible/verification/checks/snippet.ex
  lib/plausible/verification/checks/snippet_cache_bust.ex
  lib/plausible/verification/diagnostics.ex
  lib/plausible/verification/state.ex
  lib/plausible/verification/url.ex
  lib/plausible_web/components/generic.ex
  lib/plausible_web/controllers/site_controller.ex
  lib/plausible_web/controllers/stats_controller.ex
  lib/plausible_web/live/components/verification.ex
  lib/plausible_web/live/verification.ex
  lib/plausible_web/templates/site/settings_general.html.heex
  lib/plausible_web/templates/site/snippet.html.heex
  lib/plausible_web/templates/stats/waiting_first_pageview.html.heex
  mix.exs
  mix.lock
  priv/verification/verify_plausible_installed.js
  test/plausible/ingestion/event_test.exs
  test/plausible/site/verification/checks/csp_test.exs
  test/plausible/site/verification/checks/fetch_body_test.exs
  test/plausible/site/verification/checks/scan_body_test.exs
  test/plausible/site/verification/checks/snippet_test.exs
  test/plausible/site/verification/checks_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
  test/plausible_web/live/components/verification_test.exs
  test/plausible_web/live/shields/hostnames_test.exs
  test/plausible_web/live/verification_test.exs
  test/support/html.ex
  test/test_helper.exs
  tracker/src/plausible.js
Labels: deploy-to-staging, preview

#4144 Include docs anchors in diagnostic message links
  lib/plausible/verification/errors.ex
Labels: deploy-to-staging, preview

#4158 make Plausible.ce? and Plausible.ee? into functions
  lib/plausible.ex
Labels: deploy-to-staging

#4155 Populate site_imports from sites.imported_data in CE
  lib/plausible/data_migration/site_imports.ex
  lib/plausible/data_migration/versioned_sessions.ex
  priv/repo/migrations/20240528115149_migrate_site_imports.exs
  priv/repo/seeds.exs
Labels: deploy-to-staging

#4159 Make React frontend capable of reading API results under a results key
  assets/js/dashboard/stats/locations/index.js
  assets/js/dashboard/stats/locations/map.js
  assets/js/dashboard/stats/modals/conversions.js
  assets/js/dashboard/stats/modals/entry-pages.js
  assets/js/dashboard/stats/modals/exit-pages.js
  assets/js/dashboard/stats/modals/pages.js
  assets/js/dashboard/stats/modals/props.js
  assets/js/dashboard/stats/modals/referrer-drilldown.js
  assets/js/dashboard/stats/modals/sources.js
  assets/js/dashboard/stats/modals/table.js
  assets/js/dashboard/stats/reports/list.js
Labels: deploy-to-staging, preview
