Repository plausible/analytics, pull requests merged in 2025-09, with the labels that each got.

#5669 Script v2: Verifier accepts cookies
  lib/plausible/installation_support/checks/installation_v2.ex
  lib/plausible/installation_support/verification/diagnostics.ex
  test/plausible/installation_support/verification/diagnostics_test.exs
  tracker/compiler/index.js
  tracker/installation_support/autoconsent-rules/autoconsent/cookiebot.json
  tracker/installation_support/autoconsent-to-cookies.js
  tracker/installation_support/verifier-v2.js
  tracker/npm_package/CHANGELOG.md
  tracker/package-lock.json
  tracker/package.json
  tracker/test/fixtures/cookies-cookiebot.html
  tracker/test/fixtures/cookies-iubenda.html
  tracker/test/fixtures/cookies-onetrust.html
  tracker/test/fixtures/cookies-quantcast.html
  tracker/test/installation_support/verifier-v2.spec.ts
  tracker/test/support/types.ts
Labels: preview, tracker-release: patch

#5689 Enable filtering Seratch Console properties via ComboBox live component
  CHANGELOG.md
  lib/plausible_web/live/plain_combo.ex
  lib/plausible_web/templates/site/settings_integrations.html.heex
Labels: preview

#5691 Script v2: Adds linter and prettier, satisfies linter
  .github/workflows/node.yml
  tracker/.eslintrc.json
  tracker/.prettierignore
  tracker/.prettierrc.json
  tracker/compiler/index.js
  tracker/eslint.config.mjs
  tracker/installation_support/autoconsent-to-cookies.js
  tracker/installation_support/verifier-v2.js
  tracker/npm_package/CHANGELOG.md
  tracker/package-lock.json
  tracker/package.json
  tracker/src/autocapture.js
  tracker/src/config.js
  tracker/src/custom-events.js
  tracker/src/track.js
  tracker/test/callbacks.spec.ts
  tracker/test/custom-properties.spec.ts
  tracker/test/file-downloads.spec.ts
  tracker/test/hash-based-routing.spec.ts
  tracker/test/logging.spec.ts
  tracker/test/outbound-links.spec.ts
  tracker/test/plausible-npm-init.spec.ts
  tracker/test/plausible-web-init.spec.ts
  tracker/test/scroll-depth.spec.js
  tracker/test/support/initialize-page-dynamically.ts
  tracker/test/support/installation-support-playwright-wrappers.ts
  tracker/test/support/types.ts
  tracker/test/tagged-events.spec.ts
  tracker/test/transform_request.spec.ts
Labels: tracker-release: patch

#5698 Trim month, year, day periods to local now on main graph
  CHANGELOG.md
  assets/js/types/query-api.d.ts
  lib/plausible/stats/filters/query_parser.ex
  lib/plausible/stats/legacy/legacy_query_builder.ex
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_optimizer.ex
  lib/plausible/stats/timeseries.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  priv/json-schemas/query-api-schema.json
  test/plausible/stats/query_optimizer_test.exs
  test/plausible/stats/query_parser_test.exs
  test/plausible/stats/query_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_comparisons_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Labels: preview

#5694 Stats: Rebuild session smearing for timeseries
  CHANGELOG.md
  lib/plausible/stats/query.ex
  lib/plausible/stats/query_optimizer.ex
  lib/plausible/stats/sql/expression.ex
  lib/plausible/stats/sql/query_builder.ex
  lib/plausible/stats/table_decider.ex
  test/plausible/stats/query_optimizer_test.exs
  test/plausible/stats/table_decider_test.exs
  test/plausible_web/controllers/api/external_stats_controller/query_test.exs
Labels: preview

#5726 Make visual tweaks to the dashboard
  assets/css/app.css
  assets/js/dashboard/index.tsx
  assets/js/dashboard/stats/behaviours/index.js
  assets/js/dashboard/stats/graph/graph-util.js
  assets/js/dashboard/stats/graph/visitor-graph.js
  assets/js/dashboard/stats/reports/list.tsx
  assets/tailwind.config.js
  lib/plausible_web/live/sites.ex
  lib/plausible_web/templates/layout/_header.html.heex
Labels: preview
