Repository plausible/analytics, pull requests merged in 2025-01, with the labels that each got.

#4933 Fix docker build + FE test
  Dockerfile
  assets/js/dashboard/query-dates.test.tsx
Labels: preview

#4674 Autogenerate text emails
  CHANGELOG.md
  lib/plausible_web/email.ex
  mix.exs
  mix.lock
  test/plausible/imported/csv_importer_test.exs
  test/plausible_web/email_test.exs
  test/workers/notify_exported_analytics_test.exs
Labels: self-hosting, preview

#4885 Log Mailer errors
  lib/plausible/mailer.ex
Labels: preview

#4934 Consolidate dropdowns
  assets/tailwind.config.js
  lib/plausible_web/components/generic.ex
  lib/plausible_web/live/sites.ex
  lib/plausible_web/templates/layout/_header.html.heex
  lib/plausible_web/templates/site/settings_people.html.heex
Labels: preview

#4915 Average Scroll Depth Metric: imported data
  lib/plausible/exports.ex
  lib/plausible/imported/csv_importer.ex
  lib/plausible/imported/page.ex
  lib/plausible/stats/imported/imported.ex
  lib/plausible/stats/imported/sql/expression.ex
  lib/plausible/stats/sql/special_metrics.ex
  lib/plausible_web/controllers/api/stats_controller.ex
  lib/plausible_web/live/csv_export.ex
  lib/workers/export_analytics.ex
  test/plausible/exports_test.exs
  test/plausible/imported/csv_importer_test.exs
  test/plausible_web/controllers/api/stats_controller/imported_test.exs
  test/plausible_web/controllers/api/stats_controller/main_graph_test.exs
  test/plausible_web/controllers/api/stats_controller/pages_test.exs
  test/plausible_web/controllers/api/stats_controller/top_stats_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
Labels: preview

#4945 [WIP] Pin nodejs version to be the same as .tool-versions
  .github/workflows/build-private-images-ghcr.yml
  Dockerfile
Labels: preview

#4950 Fix race condition loading breakdown modals
  assets/js/dashboard/stats/modals/breakdown-modal.tsx
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/stats/reports/metric-value.tsx
Labels: preview

#4948 Implement service for inviting to a team
  lib/plausible/teams/invitation.ex
  lib/plausible/teams/invitations.ex
  lib/plausible/teams/invitations/invite_to_team.ex
  lib/plausible/teams/membership.ex
  lib/plausible_web/email.ex
  lib/plausible_web/live/register_form.ex
  lib/plausible_web/templates/email/existing_user_team_invitation.html.heex
  lib/plausible_web/templates/email/new_user_team_invitation.html.heex
  test/plausible/teams/invitations/invite_to_team_test.exs
  test/plausible_web/live/register_form_test.exs
  test/support/teams/test.ex
Labels: preview

#4916 Add return_to behaviour to 404 -> login flow
  lib/plausible_web/controllers/auth_controller.ex
  lib/plausible_web/plugs/require_account.ex
  lib/plausible_web/templates/auth/login_form.html.heex
  lib/plausible_web/templates/auth/verify_2fa.html.heex
  lib/plausible_web/templates/error/404_error.html.heex
  lib/plausible_web/user_auth.ex
  lib/plausible_web/views/error_view.ex
  test/plausible_web/controllers/auth_controller_test.exs
  test/plausible_web/controllers/stats_controller_test.exs
  test/plausible_web/plugs/user_session_touch_test.exs
  test/plausible_web/user_auth_test.exs
Labels: preview

#4960 Implement Team setup CTA+view
  extra/lib/plausible_web/live/funnel_settings/form.ex
  lib/plausible/teams.ex
  lib/plausible/teams/invitations/candidates.ex
  lib/plausible/teams/invitations/invite_to_team.ex
  lib/plausible/teams/team.ex
  lib/plausible_web/live/components/combo_box.ex
  lib/plausible_web/live/components/form.ex
  lib/plausible_web/live/team_setup.ex
  lib/plausible_web/router.ex
  lib/plausible_web/templates/layout/_header.html.heex
  priv/repo/seeds.exs
  test/plausible/teams/invitations/candidates_test.exs
  test/plausible_web/live/components/combo_box_test.exs
  test/plausible_web/live/team_setup_sync_test.exs
  test/plausible_web/live/team_setup_test.exs
  test/support/html.ex
  test/support/test_utils.ex
Labels: preview

#4991 Implement migration adding UUID identifier to team
  priv/repo/migrations/20250120095114_add_teams_identifier.exs
Labels: preview

#4990 Remove "priority" Postmark message stream from CE
  lib/plausible_web/email.ex
  test/plausible_web/email_test.exs
Labels: self-hosting

#4985 Backfill teams CE in a single transaction
  lib/plausible/data_migration/backfill_teams.ex
  priv/repo/migrations/20250117122435_backfill_teams.exs
Labels: self-hosting

#5007 Keybind and modal refactor
  assets/js/dashboard/components/search-input.tsx
  assets/js/dashboard/datepicker.tsx
  assets/js/dashboard/keybinding.tsx
  assets/js/dashboard/stats/modals/modal.js
  lib/plausible/segments/segment.ex
Labels: preview

#4983 Excluding goals in dashboard
  CHANGELOG.md
  assets/js/dashboard/components/filter-operator-selector.js
  assets/js/dashboard/filters.js
  assets/js/dashboard/nav-menu/filter-pills-list.tsx
  assets/js/dashboard/nav-menu/filters-bar.test.tsx
  assets/js/dashboard/stats/modals/filter-modal-group.js
  assets/js/dashboard/stats/modals/filter-modal-props-row.js
  assets/js/dashboard/stats/modals/filter-modal-row.js
  assets/js/dashboard/stats/reports/list.js
  assets/js/dashboard/util/filter-text.test.tsx
  assets/js/dashboard/util/filter-text.tsx
  assets/js/dashboard/util/filters.js
  assets/js/dashboard/util/filters.test.ts
  lib/plausible/stats/query.ex
Labels: preview

#5021 Expand segments also when using Query.from
  assets/js/dashboard/util/filter-text.test.tsx
  assets/js/dashboard/util/filter-text.tsx
  lib/plausible/stats/legacy/legacy_query_builder.ex
  test/plausible/stats/table_decider_test.exs
  test/plausible_web/controllers/api/stats_controller/countries_test.exs
Labels: preview

#5002 Create migration adding `is_autocreated` to `team_memberships`
  priv/repo/migrations/20250122100320_add_autocreated_to_team_memberships.exs
Labels: preview

#5028 Change `team_memberships.is_autocreated` default to `true`
  priv/repo/migrations/20250129120520_change_team_memberships_is_autocreated_default_to_true.exs
Labels: preview

#5003 Rework team creation constraints
  lib/plausible/teams.ex
  lib/plausible/teams/billing.ex
  lib/plausible/teams/grace_period.ex
  lib/plausible/teams/membership.ex
  lib/plausible/teams/team.ex
  lib/plausible_web/templates/layout/_notice.html.heex
  test/plausible/billing/billing_test.exs
  test/plausible/billing/site_locker_test.exs
  test/plausible/teams/grace_period_test.exs
  test/workers/check_usage_test.exs
Labels: preview

#5004 Drop `one_team_per_user` constraint from `team_memberships`
  priv/repo/migrations/20250129132629_drop_old_one_team_per_user_constraint.exs
Labels: preview

#5031 Don't preload goal settings modal to avoid issues with opening in edit mode
  lib/plausible_web/live/components/modal.ex
  lib/plausible_web/live/goal_settings.ex
  test/plausible_web/live/goal_settings_test.exs
Labels: preview
